consultor:
    resource: "@consultorBundle/Resources/config/routing.yml"
    prefix:   /

administrador:
    resource: "@administradorBundle/Resources/config/routing.yml"
    prefix:   /

treballador:
    resource: "@treballadorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
