<?php

namespace administradorBundle\Repository;

/**
 * ProjecteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjecteRepository extends \Doctrine\ORM\EntityRepository
{
}
