<?php

namespace administradorBundle\Repository;

/**
 * TascaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TascaRepository extends \Doctrine\ORM\EntityRepository
{
}
