<?php

namespace administradorBundle\Repository;

/**
 * UsuariRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariRepository extends \Doctrine\ORM\EntityRepository
{
}
